# Generated by Django 3.2.4 on 2021-06-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, choices=[('DE', 'developer'), ('SE', 'Software engineer'), ('DA', 'Data Analist')], max_length=2, null=True),
        ),
    ]
