# Generated by Django 3.2.4 on 2022-01-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_developer_account',
            field=models.BooleanField(default=False),
        ),
    ]
